# Generated by Django 4.2 on 2023-04-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cover_art', models.ImageField(upload_to='albums/')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='musics/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiclabapp.album')),
            ],
        ),
    ]
