# Generated by Django 4.2 on 2023-04-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0002_album_album_music_genero_music_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album',
        ),
        migrations.RemoveField(
            model_name='music',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='music',
            name='responsavel',
        ),
    ]
