# Generated by Django 4.2 on 2023-04-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0003_remove_album_album_remove_music_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(upload_to='cover_art'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
