# Generated by Django 4.2 on 2023-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0004_alter_album_cover_art_alter_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover_art'),
        ),
    ]
