# Generated by Django 4.2 on 2023-04-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0005_alter_album_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
