# Generated by Django 4.2 on 2023-04-08 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0008_music_genero_music_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='musiclabapp.album'),
        ),
    ]
