# Generated by Django 4.2 on 2023-04-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0011_alter_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genero',
            field=models.CharField(blank=True, choices=[('axe', 'Axé'), ('blues', 'Blues'), ('country', 'Country'), ('eletronica', 'Eletrônica'), ('forro', 'Forró'), ('funk', 'Funk'), ('gospel', 'Gospel'), ('hip_hop', 'Hip Hop'), ('jazz', 'Jazz'), ('mpb', 'MPB'), ('musica_classica', 'Música Clássica'), ('pagode', 'Pagode'), ('pop', 'Pop'), ('rap', 'Rap'), ('reggae', 'Reggae'), ('rock', 'Rock'), ('samba', 'Samba')], max_length=20, null=True),
        ),
    ]
