# Generated by Django 4.2 on 2023-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclabapp', '0012_alter_music_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(error_messages={'blank': 'Este campo é obrigatório.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='genero',
            field=models.CharField(blank=True, choices=[('axe', 'Axé'), ('blues', 'Blues'), ('country', 'Country'), ('eletronica', 'Eletrônica'), ('forro', 'Forró'), ('funk', 'Funk'), ('gospel', 'Gospel'), ('hip_hop', 'Hip Hop'), ('jazz', 'Jazz'), ('mpb', 'MPB'), ('musica_classica', 'Música Clássica'), ('pagode', 'Pagode'), ('pop', 'Pop'), ('rap', 'Rap'), ('reggae', 'Reggae'), ('rock', 'Rock'), ('metal', 'Metal'), ('hardcore', 'Hardcore'), ('punk', 'Punk'), ('samba', 'Samba')], max_length=20, null=True),
        ),
    ]
